# Generated by Django 3.2.3 on 2021-06-28 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ePoliceApp', '0002_auto_20210628_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='DateOfCrime',
            field=models.DateField(default=datetime.datetime(2021, 6, 28, 11, 1, 28, 881604)),
        ),
    ]
